version: '3.5'

services:
  nginx:
    image: nginx
    container_name: felichita-nginx
    ports:
      - '8081:80'
    volumes:
      - './.docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf'
      - './:/code'

  web:
    container_name: felichita-web
    build:
      dockerfile: Dockerfile
      context: ./
    tty: true
    volumes:
      - './:/code'